services:
  validator:
    image: ghcr.io/pufferfinance/validator:v0.1.2
    build:
      context: ../..
      dockerfile: ./container/Dockerfile
      args:
        BINARY_NAME: validator
    ports:
      - "9002:9001"
    env_file:
      - ./env
    volumes:
      - ./network_config.json:/config/network_config.json:ro
      - validator-data:/data
      - ./cvm-agent.sock:/app/cvm-agent.sock

volumes:
  validator-data:
