services:
  guardian:
    image: ghcr.io/pufferfinance/guardian:v0.1.1
    build:
      context: ../..
      dockerfile: ./container/Dockerfile
      args:
        BINARY_NAME: guardian
    ports:
      - "9001:9001"
    env_file:
      - ./env
    volumes:
      - ./network_config.json:/config/network_config.json:ro
      - guardian-data:/data
      - ./cvm-agent.sock:/app/cvm-agent.sock

volumes:
  guardian-data:
